version: "3.8"

services:
  rstudio:
    image: sagebionetworks/challenge-analysis:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challenge-analysis-rstudio
    environment:
      - USER=${RSTUDIO_USER}
      - PASSWORD=${RSTUDIO_PASSWORD}
      - USERID=${RSTUDIO_USERID}
      - GROUPID=${RSTUDIO_GROUPID}
      - ROOT=${RSTUDIO_ROOT}
      - SYNAPSE_USERNAME
      - SYNAPSE_API_KEY
    volumes:
      - .:/home/rstudio/challenge-analysis:rw
    ports:
      - "${HOST_PORT}:8787"